import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { Toaster } from "sonner";
  
const Clash = localFont({ src: "./Clash_Regular.otf"})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Bet Royale</title>
      </head>
      <body
        className={`${Clash.className} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
